Uspacy/uspacy-store

package.json, src/store/payments/index.ts
=> fix: adding_set_tariff_action_type

package.json, src/store/crmEntities/actions.ts, src/store/crmEntities/index.ts, src/store/crmEntities/types.ts, src/store/index.ts, yarn.lock
=> adding crm entities

package.json, src/store/auth/actions.ts, src/store/auth/index.ts, src/store/auth/types.ts, src/store/payments/index.ts, src/store/payments/types.ts, yarn.lock
- Added create using payment intent
=> feature: Adding create using payment intent

package.json, src/helpers/stringsHelper.ts, src/store/tasks/actions.ts, src/store/tasks/index.ts, yarn.lock
- Added mass editing to tasks service
=> feature: adding mass editing

package.json, src/store/tasks/actions.ts, src/store/tasks/index.ts, src/store/tasks/types.ts, yarn.lock
=> feature: adding tasks fields

package.json, src/store/tasks/actions.ts, src/store/tasks/index.ts, yarn.lock
=> feature: Updating mass actions

package.json, src/store/users/index.ts, yarn.lock
=> feature: filtering application users

package.json, src/store/crmEntities/index.ts
=> feature: updating entities

package.json, src/store/tasksStages/index.ts
- added clearing kanban stages
=> [1702] fix: fixing clearing kanban stages

package.json, src/store/tasks/index.ts
- Added ability to filling multiple users
=> [1708]: add filling multiple users

package.json, yarn.lock
=> [1841] fix: updating payments

package.json, src/store/groups/actions.ts, src/store/groups/index.ts, src/store/groups/types.ts, src/store/tasks/index.ts, yarn.lock
- Added getGroupForTask and methods for store
=> [1896] fix: fixing edit tasks in groups

package.json
=> fix: fixing dependencies

package.json, yarn.lock
- Updated uspacy store version
=> [2070] feature: update usapcy store version

package.json, src/store/email/actions.ts, src/store/email/types.ts, yarn.lock
- Updated email params for letters
=> [2070] feature: update email params for letters

package.json, src/store/email/index.ts, yarn.lock
=> [2070] feature: update email filters

package.json, src/store/email/actions.ts, src/store/email/types.ts, yarn.lock
=> fix: Update types for email

package.json, src/store/tasks/index.ts
fixed default boolean operator
=> [2585] fix: fix default boolean operator

package.json, src/store/tasks/index.ts
=> [2462] feature: remove unallocated column

package.json, src/store/tasks/actions.ts, src/store/tasks/index.ts, src/store/tasks/types.ts, yarn.lock
- Added replicate method to tasks
=> [2423] feature: add replicate method to tasks

package.json, src/store/crmTasks/index.ts
Changes paginations params in initial crmTasks filter
1. page -> 1
2. perPage -> 20
=> [3051] disability to set page size

package.json, src/store/crmCompanies/index.ts, src/store/crmDocumentTemplates/actions.ts, src/store/tasks/actions.ts, src/store/tasks/index.ts, src/store/tasksStages/actions.ts, yarn.lock
- Added delegation task method
=> [2045] feature: delegation of tasks store

package.json, src/store/users/index.ts, src/store/users/types.ts
- Updated users state for loading and error
=> [3198] feature: update loaders for profile service

package.json, src/store/email/actions.ts, src/store/email/index.ts, src/store/email/types.ts, yarn.lock
- Added actions for microsoft OAuth and updated reducers for emails
=> [3432] feature: OAuth microsoft integration store

package.json, yarn.lock
=> [4155] feature: up sdk v

package.json, yarn.lock
=> [4540] feature: email access by users and signature/store

package.json, src/store/roles/index.ts
Reverts Uspacy/uspacy-store#188
=> 4544 permission logic

package.json, src/store/crm/items/types.ts
=> [3396] feature: new crm kanban
